# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19wYFvYt3oLorSJZKrT_5snRYu0aynyaS
"""

from IPython.core.display import display, HTML
html_code = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background: #f4f4f9;
            color: #333;
        }
        header {
            background: #333;
            color: white;
            padding: 1rem;
            text-align: center;
        }
        header h1 {
            margin: 0;
            font-size: 2.5rem;
        }
        nav {
            background: #444;
            padding: 0.5rem;
            text-align: center;
        }
        nav a {
            color: white;
            text-decoration: none;
            margin: 0 1rem;
            font-weight: bold;
        }
        nav a:hover {
            color: #ff5722;
        }
        .hero {
            background: #009688;
            color: white;
            padding: 4rem 2rem;
            text-align: center;
        }
        .hero h2 {
            font-size: 2rem;
        }
        .hero p {
            margin: 1rem 0;
            font-size: 1.2rem;
        }
        .content {
            padding: 2rem;
            text-align: center;
        }
        .content h2 {
            color: #009688;
        }
        .content .card {
            display: inline-block;
            margin: 1rem;
            padding: 1rem;
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            width: 250px;
            background: #fff;
        }
        .content .card h3 {
            margin-top: 0;
        }
        footer {
            background: #333;
            color: white;
            padding: 1rem;
            text-align: center;
        }
    </style>
    <script>
        function showAlert() {
            alert("Thank you for visiting my portfolio!");
        }
    </script>
</head>
<body>
    <header>
        <h1>My Portfolio</h1>
    </header>
    <nav>
        <a href="#about">About</a>
        <a href="#projects">Projects</a>
        <a href="#contact">Contact</a>
    </nav>
    <section class="hero">
        <h2>Welcome to My Portfolio</h2>
        <p>Explore my work, projects, and achievements.</p>
        <button onclick="showAlert()">Click Me</button>
    </section>
    <section id="about" class="content">
        <h2>About Me</h2>
        <p>I am a passionate developer with expertise in building modern and responsive web applications.</p>
    </section>
    <section id="projects" class="content">
        <h2>My Projects</h2>
        <div class="card">
            <h3>Project 1</h3>
            <p>A web application for task management.</p>
        </div>
        <div class="card">
            <h3>Project 2</h3>
            <p>An e-commerce website for online shopping.</p>
        </div>
        <div class="card">
            <h3>Project 3</h3>
            <p>A portfolio site to showcase my work.</p>
        </div>
    </section>
    <section id="contact" class="content">
        <h2>Contact Me</h2>
        <p>Email: myemail@example.com</p>
        <p>Phone: +123 456 7890</p>
    </section>
    <footer>
        &copy; 2024 My Portfolio. All rights reserved.
    </footer>
</body>
</html>
"""
display(HTML(html_code))